### ISSUE TITLE
Migration from v1 to v2 on local MongoDB server

### ISSUE THREAD

**Issue by mapolone** [LearningLocker/v1-to-v2-migrator#13]
Hello,
is there any way to migrate database from v1 to v2 using the same MongoDB server?

Since I only have (for now) a dump of the older database, this has been imported using a different name (let's say, learninglocker_v1). Hence, I followed the documentation of migrator and created a `config.json` [file](https://gist.github.com/mapolone/7901ad45da970ee6cd4ab2f12e682494).

Then I launched the following command:
`./bin/migrater config/config.json`

Anyway, fields `lrsId` and `orgId` are not present in README, and [this issue](https://github.com/LearningLocker/v1-to-v2-migrator/issues/10) refers to `target.organisation` that's not documented nor present in example.json file.

I've replaced `orgId` with `organisation` in config.json file, but still no luck.

**Comment by ryansmith94** [comment]
Hi @mapolone, you can migrate a v1 database to a v2 database on the same MongoDB server by changing the config, assuming the two databases have different names. I'm not sure if what you actually wanted was to migrate over the existing v1 database.

Good spot with the mistake in the readme, the property should be `orgId` [according to the code](https://github.com/LearningLocker/v1-to-v2-migrator/blob/master/src/migrateLocalData.js#L22).

**Comment by mapolone** [comment]
Hi @ryansmith94, exactly, I wanted to migrate all the v1 database over the new one. Is this the proper procedure?

**Comment by ryansmith94** [comment]
Hi @mapolone, there's not currently a way to configure this to do that, however, I can see that it wouldn't be too difficult to [modify the code](https://github.com/LearningLocker/v1-to-v2-migrator/blob/master/src/localConnect.js#L4) to achieve this.
