### ISSUE TITLE
"ReferenceError: sourceDB is not defined" trying to migrate

### ISSUE THREAD

**Issue by mapolone** [LearningLocker/v1-to-v2-migrator#15]
Hello, I'm still trying to migrate version 1 of database towards version 2 (see this [issue](https://github.com/LearningLocker/v1-to-v2-migrator/issues/13))

After the last pull from repository I have this error:
`ReferenceError: sourceDB is not defined`
seems like `database` should be renamed to `DB` or `Db`, but still doesn't work.
Any idea how to fix this?

**Comment by ht2** [comment]
Thanks @mapolone - looks like this line is wrong: https://github.com/LearningLocker/v1-to-v2-migrator/blob/master/src/dumpSourceData.js#L15
